spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgreis
    username: dev
    password: dev
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      show-sql: true
